import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await (await b.newContext({ viewport:{width:1280,height:720} })).newPage();
await p.goto('https://kaenden.github.io/corrupted-exe/',{waitUntil:'load'});
await p.waitForFunction(()=>window.GameState?.data && window.game?.scene?.isActive('MenuScene'),undefined,{timeout:20000});
await p.evaluate(()=>{window.game.scene.stop('MenuScene');window.game.scene.start('GameScene',{world:'alpha',levelIndex:0});});
await p.waitForTimeout(500);
await p.evaluate(()=>{['UIScene','GameScene'].forEach(k=>{const c=window.game.scene.getScene(k).cameras.main;c.fadeEffect&&c.fadeEffect.reset();c.resetFX&&c.resetFX();});});
await p.waitForTimeout(120);
await p.screenshot({ path:'p3-intro.png' });
console.log('shot');
await b.close();
