import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await (await b.newContext({ viewport:{width:1280,height:720} })).newPage();
await p.goto('https://kaenden.github.io/corrupted-exe/',{waitUntil:'load'});
await p.waitForFunction(()=>window.GameState?.data && window.game?.scene?.isActive('MenuScene'),undefined,{timeout:20000});
await p.evaluate(()=>{window.game.scene.stop('MenuScene');window.game.scene.start('GameScene',{world:'alpha',levelIndex:0});});
await p.waitForTimeout(450);
const n=await p.evaluate(()=>{const ui=window.game.scene.getScene('UIScene');let cards=0;ui.children.list.forEach(o=>{if(o.type==='Container')cards++;});return{uiActive:window.game.scene.isActive('UIScene'),containers:cards};});
console.log('UI '+JSON.stringify(n));
await p.screenshot({ path:'p3-intro.png' });
await b.close();
